# Generated by Django 5.1.2 on 2025-11-11 00:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_district_module_media_and_unlocks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('idle', 'Idle'), ('asking', 'Asking'), ('waiting', 'Waiting'), ('completed', 'Completed')], default='asking', max_length=16)),
                ('current_step_id', models.CharField(blank=True, max_length=64)),
                ('current_order', models.IntegerField(default=0)),
                ('total_steps', models.IntegerField(default=0)),
                ('flow_version', models.CharField(blank=True, max_length=32)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LessonStepResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.CharField(max_length=64)),
                ('field_name', models.CharField(max_length=128)),
                ('value', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='exercisesubmission',
            new_name='myApp_exerc_user_id_ca00b8_idx',
            old_name='myApp_exer_user_id_aed519_idx',
        ),
        migrations.RenameIndex(
            model_name='telemetryevent',
            new_name='myApp_telem_module__dada24_idx',
            old_name='myApp_tele_module__5a3288_idx',
        ),
        migrations.RenameIndex(
            model_name='userprogress',
            new_name='myApp_userp_user_id_85edaa_idx',
            old_name='myApp_user__user_id_744e54_idx',
        ),
        migrations.AlterField(
            model_name='exercisesubmission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='uservenueunlock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='lessonsession',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guided_sessions', to='myApp.module'),
        ),
        migrations.AddField(
            model_name='lessonsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guided_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonstepresponse',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='myApp.lessonsession'),
        ),
        migrations.AddIndex(
            model_name='lessonsession',
            index=models.Index(fields=['user', 'module', 'state'], name='myApp_lesso_user_id_c5a07c_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonstepresponse',
            index=models.Index(fields=['session', 'step_id'], name='myApp_lesso_session_a3c478_idx'),
        ),
    ]
