# Generated by Django 5.1.2 on 2025-11-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_amphitheatre_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='amphitheatreexerciserecord',
            new_name='myApp_amphi_session_cd7fd1_idx',
            old_name='amphi_record_state_idx',
        ),
        migrations.RenameIndex(
            model_name='amphitheatreexerciserecord',
            new_name='myApp_amphi_session_1a60b2_idx',
            old_name='amphi_record_seq_idx',
        ),
        migrations.RenameIndex(
            model_name='amphitheatresession',
            new_name='myApp_amphi_user_id_8ab539_idx',
            old_name='amphi_session_user_status_idx',
        ),
        migrations.RenameIndex(
            model_name='amphitheatresession',
            new_name='myApp_amphi_user_id_6bb46a_idx',
            old_name='amphi_session_visit_idx',
        ),
        migrations.AlterField(
            model_name='lessonsession',
            name='state',
            field=models.CharField(choices=[('idle', 'Idle'), ('asking', 'Asking'), ('waiting', 'Waiting'), ('transitioning', 'Transitioning'), ('completed', 'Completed')], default='asking', max_length=16),
        ),
    ]
